/******************************************************************************/
/* */
/* SCRIPT DE CRIAÇÃO PARA FIREBIRD 3.0+                       */
/* */
/******************************************************************************/
/*
   ATENÇÃO: A criação do banco e do usuário no Firebird é feita manually
   antes de executar este script.
   ... (instruções mantidas) ...
*/
/******************************************************************************/

SET AUTODDL OFF;
SET TERM ^;

-- Bloco para remover tabelas existentes, se houver
EXECUTE BLOCK AS
BEGIN
  IF (EXISTS(SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'LOG_ALTERACOES')) THEN
    EXECUTE STATEMENT 'DROP TABLE LOG_ALTERACOES;';
  IF (EXISTS(SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'VEGETAIS')) THEN
    EXECUTE STATEMENT 'DROP TABLE VEGETAIS;';
  IF (EXISTS(SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'TIPOS_VEGETAIS')) THEN
    EXECUTE STATEMENT 'DROP TABLE TIPOS_VEGETAIS;';
  IF (EXISTS(SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'USUARIOS')) THEN
    EXECUTE STATEMENT 'DROP TABLE USUARIOS;';
  IF (EXISTS(SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'ESPECIE_GATOS')) THEN
    EXECUTE STATEMENT 'DROP TABLE ESPECIE_GATOS;';
END^
SET TERM ;^
COMMIT;

-- Tabela de Usuários
CREATE TABLE USUARIOS (
    LOGIN_USUARIO VARCHAR(255) CHARACTER SET UTF8 NOT NULL PRIMARY KEY,
    SENHA_CRIPTOGRAFADA VARCHAR(255) CHARACTER SET UTF8 NOT NULL,
    NOME_COMPLETO VARCHAR(255) CHARACTER SET UTF8 NOT NULL,
    TIPO_ACESSO VARCHAR(100) CHARACTER SET UTF8 NOT NULL CHECK (TIPO_ACESSO IN (
        'Administrador Global', 'Diretor de Operações', 'Gerente de TI',
        'Supervisor de Produção', 'Operador de Linha', 'Analista de Dados', 'Auditor Externo'
    ))
);

-- Tabela de Tipos de Vegetais
CREATE TABLE TIPOS_VEGETAIS (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOME VARCHAR(100) CHARACTER SET UTF8 NOT NULL UNIQUE
);

-- Tabela de Vegetais com Chave Estrangeira
CREATE TABLE VEGETAIS (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOME VARCHAR(100) CHARACTER SET UTF8 NOT NULL,
    ID_TIPO INTEGER,
    FOREIGN KEY (ID_TIPO) REFERENCES TIPOS_VEGETAIS(ID) ON DELETE SET NULL ON UPDATE CASCADE
);

-- Tabela de Log de Alterações
CREATE TABLE LOG_ALTERACOES (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TIMESTAMP TIMESTAMP NOT NULL,
    LOGIN_USUARIO VARCHAR(255) CHARACTER SET UTF8,
    ACAO BLOB SUB_TYPE TEXT CHARACTER SET UTF8,
    FOREIGN KEY (LOGIN_USUARIO) REFERENCES USUARIOS(LOGIN_USUARIO) ON DELETE SET NULL ON UPDATE CASCADE
);

-- Tabela Especie Gatos
CREATE TABLE ESPECIE_GATOS (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOME_ESPECIE VARCHAR(255) CHARACTER SET UTF8 NOT NULL UNIQUE,
    PAIS_ORIGEM VARCHAR(255) CHARACTER SET UTF8,
    TEMPERAMENTO VARCHAR(255) CHARACTER SET UTF8
);
COMMIT;

INSERT INTO USUARIOS (LOGIN_USUARIO, SENHA_CRIPTOGRAFADA, NOME_COMPLETO, TIPO_ACESSO) VALUES
('admin', '$2b$12$TgcQ51usbRmBjfGtris6eueXiKMbJpfSpsFpuyM4QE/qwqmcEX9By', 'Usuário Administrador', 'Administrador Global'),
('diretor.op', '$2b$12$TgcQ51usbRmBjfGtris6eueXiKMbJpfSpsFpuyM4QE/qwqmcEX9By', 'Carlos Diretor', 'Diretor de Operações'),
('gerente.ti', '$2b$12$TgcQ51usbRmBjfGtris6eueXiKMbJpfSpsFpuyM4QE/qwqmcEX9By', 'Beatriz Gerente', 'Gerente de TI'),
('ana.supervisor', '$2b$12$TgcQ51usbRmBjfGtris6eueXiKMbJpfSpsFpuyM4QE/qwqmcEX9By', 'Ana Supervisora', 'Supervisor de Produção'),
('bruno.operador', '$2b$12$TgcQ51usbRmBjfGtris6eueXiKMbJpfSpsFpuyM4QE/qwqmcEX9By', 'Bruno Operador', 'Operador de Linha'),
('carla.analista', '$2b$12$TgcQ51usbRmBjfGtris6eueXiKMbJpfSpsFpuyM4QE/qwqmcEX9By', 'Carla Analista', 'Analista de Dados'),
('davi.auditor', '$2b$12$TgcQ51usbRmBjfGtris6eueXiKMbJpfSpsFpuyM4QE/qwqmcEX9By', 'Davi Auditor', 'Auditor Externo'),
('elisa.op', '$2b$12$TgcQ51usbRmBjfGtris6eueXiKMbJpfSpsFpuyM4QE/qwqmcEX9By', 'Elisa Operadora', 'Operador de Linha'),
('felipe.gerente', '$2b$12$TgcQ51usbRmBjfGtris6eueXiKMbJpfSpsFpuyM4QE/qwqmcEX9By', 'Felipe Gerente TI', 'Gerente de TI'),
('gabi.analista', '$2b$12$TgcQ51usbRmBjfGtris6eueXiKMbJpfSpsFpuyM4QE/qwqmcEX9By', 'Gabriela Analista', 'Analista de Dados'),
('hugo.diretor', '$2b$12$TgcQ51usbRmBjfGtris6eueXiKMbJpfSpsFpuyM4QE/qwqmcEX9By', 'Hugo Diretor', 'Diretor de Operações'),
('isa.supervisor', '$2b$12$TgcQ51usbRmBjfGtris6eueXiKMbJpfSpsFpuyM4QE/qwqmcEX9By', 'Isadora Supervisora', 'Supervisor de Produção'),
('joao.operador', '$2b$12$TgcQ51usbRmBjfGtris6eueXiKMbJpfSpsFpuyM4QE/qwqmcEX9By', 'João Operador', 'Operador de Linha'),
('lara.admin', '$2b$12$TgcQ51usbRmBjfGtris6eueXiKMbJpfSpsFpuyM4QE/qwqmcEX9By', 'Lara Administradora', 'Administrador Global'),
('mateus.auditor', '$2b$12$TgcQ51usbRmBjfGtris6eueXiKMbJpfSpsFpuyM4QE/qwqmcEX9By', 'Mateus Auditor', 'Auditor Externo');

INSERT INTO TIPOS_VEGETAIS (NOME) VALUES ('Raízes e Tubérculos');
INSERT INTO TIPOS_VEGETAIS (NOME) VALUES ('Folhas');
INSERT INTO TIPOS_VEGETAIS (NOME) VALUES ('Flores e Inflorescências');
INSERT INTO TIPOS_VEGETAIS (NOME) VALUES ('Frutos');
INSERT INTO TIPOS_VEGETAIS (NOME) VALUES ('Legumes');

INSERT INTO VEGETAIS (NOME, ID_TIPO) VALUES ('Abóbora', 4);
INSERT INTO VEGETAIS (NOME, ID_TIPO) VALUES ('Abobrinha', 4);
INSERT INTO VEGETAIS (NOME, ID_TIPO) VALUES ('Agrião', 2);
INSERT INTO VEGETAIS (NOME, ID_TIPO) VALUES ('Aipim', 1);
INSERT INTO VEGETAIS (NOME, ID_TIPO) VALUES ('Alface', 2);
INSERT INTO VEGETAIS (NOME, ID_TIPO) VALUES ('Alho', 1);
INSERT INTO VEGETAIS (NOME, ID_TIPO) VALUES ('Almeirão', 2);
INSERT INTO VEGETAIS (NOME, ID_TIPO) VALUES ('Batata-doce', 1);
INSERT INTO VEGETAIS (NOME, ID_TIPO) VALUES ('Batata', 1);
INSERT INTO VEGETAIS (NOME, ID_TIPO) VALUES ('Berinjela', 4);
INSERT INTO VEGETAIS (NOME, ID_TIPO) VALUES ('Beterraba', 1);
INSERT INTO VEGETAIS (NOME, ID_TIPO) VALUES ('Brócolis', 3);
INSERT INTO VEGETAIS (NOME, ID_TIPO) VALUES ('Cebola', 1);
INSERT INTO VEGETAIS (NOME, ID_TIPO) VALUES ('Cenoura', 1);
INSERT INTO VEGETAIS (NOME, ID_TIPO) VALUES ('Chuchu', 4);
INSERT INTO VEGETAIS (NOME, ID_TIPO) VALUES ('Coentro', 2);
INSERT INTO VEGETAIS (NOME, ID_TIPO) VALUES ('Couve', 2);
INSERT INTO VEGETAIS (NOME, ID_TIPO) VALUES ('Couve-flor', 3);
INSERT INTO VEGETAIS (NOME, ID_TIPO) VALUES ('Ervilha', 5);
INSERT INTO VEGETAIS (NOME, ID_TIPO) VALUES ('Espinafre', 2);
INSERT INTO VEGETAIS (NOME, ID_TIPO) VALUES ('Feijão-vagem', 5);
INSERT INTO VEGETAIS (NOME, ID_TIPO) VALUES ('Inhame', 1);
INSERT INTO VEGETAIS (NOME, ID_TIPO) VALUES ('Jiló', 4);
INSERT INTO VEGETAIS (NOME, ID_TIPO) VALUES ('Maxixe', 4);
INSERT INTO VEGETAIS (NOME, ID_TIPO) VALUES ('Milho', 4);
INSERT INTO VEGETAIS (NOME, ID_TIPO) VALUES ('Pepino', 4);
INSERT INTO VEGETAIS (NOME, ID_TIPO) VALUES ('Pimentão', 4);
INSERT INTO VEGETAIS (NOME, ID_TIPO) VALUES ('Quiabo', 4);
INSERT INTO VEGETAIS (NOME, ID_TIPO) VALUES ('Rabanete', 1);
INSERT INTO VEGETAIS (NOME, ID_TIPO) VALUES ('Repolho', 2);

INSERT INTO ESPECIE_GATOS (NOME_ESPECIE, PAIS_ORIGEM, TEMPERAMENTO) VALUES
('Siamês', 'Tailândia', 'Inteligente e Afetuoso'),
('Persa', 'Irã (Pérsia)', 'Calmo e Dócil'),
('Maine Coon', 'Estados Unidos', 'Gentil e Brincalhão'),
('Bengal', 'Estados Unidos', 'Ativo e Curioso');
COMMIT;