/******************************************************************************/
/* */
/* SCRIPT DE CRIAÇÃO PARA FIREBIRD 3.0+                       */
/* */
/******************************************************************************/
/*
   ATENÇÃO: A criação do banco e do usuário no Firebird é feita manualmente
   antes de executar este script.

   Passo 1: Criar o usuário 'gato' (se não existir)
   Abra o prompt de comando e navegue até a pasta 'bin' do Firebird.
   Execute: gsec -add gato -pw "-Vladmir!5Anos-"

   Passo 2: Criar o banco de dados
   Use uma ferramenta como o 'isql' ou um client gráfico (DBeaver, FlameRobin).
   Exemplo com isql:
   > CREATE DATABASE 'C:\caminho\para\seu\banco\NexlifyTTk.fdb'
     PAGE_SIZE 8192
     USER 'SYSDBA' PASSWORD 'masterkey'
     DEFAULT CHARACTER SET UTF8;
   > QUIT;

   Passo 3: Conceder direitos de administrador ao usuário 'gato' no novo banco
   > gsec -database "C:\caminho\para\seu\banco\NexlifyTTk.fdb" -user SYSDBA -password masterkey -modify gato -admin yes

   Passo 4: Conecte-se ao banco 'NexlifyTTk.fdb' com o usuário 'gato'
   e execute o script abaixo.
*/
/******************************************************************************/

-- Usar SET AUTODDL OFF é uma boa prática para evitar commits automáticos
-- e garantir que tudo seja executado em uma única transação.
SET AUTODDL OFF;
SET TERM ^;

-- Bloco para remover tabelas existentes, se houver
EXECUTE BLOCK AS
BEGIN
  IF (EXISTS(SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'LOG_ALTERACOES')) THEN
    EXECUTE STATEMENT 'DROP TABLE LOG_ALTERACOES;';
  IF (EXISTS(SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'LINGUAGENS_PROGRAMACAO')) THEN
    EXECUTE STATEMENT 'DROP TABLE LINGUAGENS_PROGRAMACAO;';
  IF (EXISTS(SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'ESPECIE_GATOS')) THEN
    EXECUTE STATEMENT 'DROP TABLE ESPECIE_GATOS;';
  IF (EXISTS(SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'TIPOS_LINGUAGEM')) THEN
    EXECUTE STATEMENT 'DROP TABLE TIPOS_LINGUAGEM;';
  IF (EXISTS(SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'USUARIOS')) THEN
    EXECUTE STATEMENT 'DROP TABLE USUARIOS;';
END^
SET TERM ;^
COMMIT;

-- Tabela de Usuários
CREATE TABLE USUARIOS (
    LOGIN_USUARIO VARCHAR(255) CHARACTER SET UTF8 NOT NULL PRIMARY KEY,
    SENHA_CRIPTOGRAFADA VARCHAR(255) CHARACTER SET UTF8 NOT NULL,
    NOME_COMPLETO VARCHAR(255) CHARACTER SET UTF8 NOT NULL,
    TIPO_ACESSO VARCHAR(100) CHARACTER SET UTF8 NOT NULL CHECK (TIPO_ACESSO IN (
        'Administrador Global', 'Diretor de Operações', 'Gerente de TI',
        'Supervisor de Produção', 'Operador de Linha', 'Analista de Dados', 'Auditor Externo'
    ))
);

-- Tabela de Tipos de Linguagem
CREATE TABLE TIPOS_LINGUAGEM (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOME VARCHAR(100) CHARACTER SET UTF8 NOT NULL UNIQUE
);

-- Tabela de Linguagens com Chave Estrangeira
CREATE TABLE LINGUAGENS_PROGRAMACAO (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOME VARCHAR(100) CHARACTER SET UTF8 NOT NULL,
    ID_TIPO INTEGER,
    ANO_CRIACAO INTEGER,
    CATEGORIA VARCHAR(100) CHARACTER SET UTF8,
    FOREIGN KEY (ID_TIPO) REFERENCES TIPOS_LINGUAGEM(ID) ON DELETE SET NULL ON UPDATE CASCADE
);

-- Tabela de Log de Alterações
CREATE TABLE LOG_ALTERACOES (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TIMESTAMP TIMESTAMP NOT NULL,
    LOGIN_USUARIO VARCHAR(255) CHARACTER SET UTF8,
    ACAO BLOB SUB_TYPE TEXT CHARACTER SET UTF8,
    FOREIGN KEY (LOGIN_USUARIO) REFERENCES USUARIOS(LOGIN_USUARIO) ON DELETE SET NULL ON UPDATE CASCADE
);

-- Tabela Especie Gatos
CREATE TABLE ESPECIE_GATOS (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOME_ESPECIE VARCHAR(255) CHARACTER SET UTF8 NOT NULL UNIQUE,
    PAIS_ORIGEM VARCHAR(255) CHARACTER SET UTF8,
    TEMPERAMENTO VARCHAR(255) CHARACTER SET UTF8
);
COMMIT;

INSERT INTO USUARIOS (LOGIN_USUARIO, SENHA_CRIPTOGRAFADA, NOME_COMPLETO, TIPO_ACESSO) VALUES
('admin', '$2b$12$TgcQ51usbRmBjfGtris6eueXiKMbJpfSpsFpuyM4QE/qwqmcEX9By', 'Usuário Administrador', 'Administrador Global'),
('diretor.op', '$2b$12$TgcQ51usbRmBjfGtris6eueXiKMbJpfSpsFpuyM4QE/qwqmcEX9By', 'Carlos Diretor', 'Diretor de Operações'),
('gerente.ti', '$2b$12$TgcQ51usbRmBjfGtris6eueXiKMbJpfSpsFpuyM4QE/qwqmcEX9By', 'Beatriz Gerente', 'Gerente de TI'),
('ana.supervisor', '$2b$12$TgcQ51usbRmBjfGtris6eueXiKMbJpfSpsFpuyM4QE/qwqmcEX9By', 'Ana Supervisora', 'Supervisor de Produção'),
('bruno.operador', '$2b$12$TgcQ51usbRmBjfGtris6eueXiKMbJpfSpsFpuyM4QE/qwqmcEX9By', 'Bruno Operador', 'Operador de Linha'),
('carla.analista', '$2b$12$TgcQ51usbRmBjfGtris6eueXiKMbJpfSpsFpuyM4QE/qwqmcEX9By', 'Carla Analista', 'Analista de Dados'),
('davi.auditor', '$2b$12$TgcQ51usbRmBjfGtris6eueXiKMbJpfSpsFpuyM4QE/qwqmcEX9By', 'Davi Auditor', 'Auditor Externo'),
('elisa.op', '$2b$12$TgcQ51usbRmBjfGtris6eueXiKMbJpfSpsFpuyM4QE/qwqmcEX9By', 'Elisa Operadora', 'Operador de Linha'),
('felipe.gerente', '$2b$12$TgcQ51usbRmBjfGtris6eueXiKMbJpfSpsFpuyM4QE/qwqmcEX9By', 'Felipe Gerente TI', 'Gerente de TI'),
('gabi.analista', '$2b$12$TgcQ51usbRmBjfGtris6eueXiKMbJpfSpsFpuyM4QE/qwqmcEX9By', 'Gabriela Analista', 'Analista de Dados'),
('hugo.diretor', '$2b$12$TgcQ51usbRmBjfGtris6eueXiKMbJpfSpsFpuyM4QE/qwqmcEX9By', 'Hugo Diretor', 'Diretor de Operações'),
('isa.supervisor', '$2b$12$TgcQ51usbRmBjfGtris6eueXiKMbJpfSpsFpuyM4QE/qwqmcEX9By', 'Isadora Supervisora', 'Supervisor de Produção'),
('joao.operador', '$2b$12$TgcQ51usbRmBjfGtris6eueXiKMbJpfSpsFpuyM4QE/qwqmcEX9By', 'João Operador', 'Operador de Linha'),
('lara.admin', '$2b$12$TgcQ51usbRmBjfGtris6eueXiKMbJpfSpsFpuyM4QE/qwqmcEX9By', 'Lara Administradora', 'Administrador Global'),
('mateus.auditor', '$2b$12$TgcQ51usbRmBjfGtris6eueXiKMbJpfSpsFpuyM4QE/qwqmcEX9By', 'Mateus Auditor', 'Auditor Externo');


INSERT INTO TIPOS_LINGUAGEM (NOME) VALUES ('Estática');
INSERT INTO TIPOS_LINGUAGEM (NOME) VALUES ('Dinâmica');
INSERT INTO TIPOS_LINGUAGEM (NOME) VALUES ('Mista');
INSERT INTO TIPOS_LINGUAGEM (NOME) VALUES ('Funcional');
INSERT INTO TIPOS_LINGUAGEM (NOME) VALUES ('Lógica');

INSERT INTO LINGUAGENS_PROGRAMACAO (NOME, ID_TIPO, ANO_CRIACAO, CATEGORIA) VALUES
('C++', 1, 1985, 'Linguagens Compiladas');
INSERT INTO LINGUAGENS_PROGRAMACAO (NOME, ID_TIPO, ANO_CRIACAO, CATEGORIA) VALUES
('Java', 1, 1995, 'Linguagens Compiladas');
INSERT INTO LINGUAGENS_PROGRAMACAO (NOME, ID_TIPO, ANO_CRIACAO, CATEGORIA) VALUES
('Rust', 1, 2010, 'Linguagens Compiladas');
INSERT INTO LINGUAGENS_PROGRAMACAO (NOME, ID_TIPO, ANO_CRIACAO, CATEGORIA) VALUES
('Python', 2, 1991, 'Linguagens Interpretadas');
INSERT INTO LINGUAGENS_PROGRAMACAO (NOME, ID_TIPO, ANO_CRIACAO, CATEGORIA) VALUES
('JavaScript', 2, 1995, 'Linguagens Interpretadas');

INSERT INTO ESPECIE_GATOS (NOME_ESPECIE, PAIS_ORIGEM, TEMPERAMENTO) VALUES
('Siamês', 'Tailândia', 'Inteligente e Afetuoso');
INSERT INTO ESPECIE_GATOS (NOME_ESPECIE, PAIS_ORIGEM, TEMPERAMENTO) VALUES
('Persa', 'Irã (Pérsia)', 'Calmo e Dócil');
INSERT INTO ESPECIE_GATOS (NOME_ESPECIE, PAIS_ORIGEM, TEMPERAMENTO) VALUES
('Maine Coon', 'Estados Unidos', 'Gentil e Brincalhão');
INSERT INTO ESPECIE_GATOS (NOME_ESPECIE, PAIS_ORIGEM, TEMPERAMENTO) VALUES
('Bengal', 'Estados Unidos', 'Ativo e Curioso');
COMMIT;