[database]
# ======================================================================
# INSTRUÇÕES DE USO:
# Para usar um banco de dados, descomente a seção correspondente
# (removendo o '#' do início de cada linha) e comente as outras.
# Apenas UMA configuração de banco de dados deve estar ativa por vez.
#
# O nome do banco de dados padrão é 'NexlifyTTk' e o usuário/senha
# padrão são 'gato' e '-Vladmir!5Anos-', conforme os scripts de
# criação manual. Ajuste se necessário.
# ======================================================================


#  Configuração para Microsoft SQL Server (ATIVA) 
# Requer um servidor SQL Server rodando e o driver pymssql.
# Instale com: pip install pymssql
#
#type = sqlserver
#host = 10.77.77.189
#port = 1433
#dbname = NexlifyTTk
#user = gato
#password = -Vladmir!5Anos-


#  Configuração para SQLite 
# Não requer instalação de servidor. O banco será um arquivo local.
# O caminho (path) é relativo à pasta raiz do projeto.

type = sqlite
path = NexlifyTTk.db


#  Configuração para PostgreSQL 
# Requer um servidor PostgreSQL rodando e o driver psycopg2.
# Instale com: pip install psycopg2-binary
#
#type = postgresql
#host = localhost
#port = 5432
#dbname = NexlifyTTk
#user = gato
#password = -Vladmir!5Anos-


#  Configuração para MySQL 
# Requer um servidor MySQL rodando e o driver PyMySQL.
# Instale com: pip install PyMySQL
#
#type = mysql
#host = localhost
#port = 3306
#dbname = NexlifyTTk
#user = gato
#password = -Vladmir!5Anos-


#  Configuração para MariaDB 
# Requer um servidor MariaDB rodando e o driver mariadb.
# Instale com: pip install mariadb
#

#type = mariadb
#host = 10.77.77.189
#port = 3306
#dbname = NexlifyTTk
#user = gAAAAABo52D7Wefg0RLLMr62vnJinZeI5CMPv46SR-QgTHB18DdC9RmvR53QM4MBQOlLj_bUo0Rouzp8LuMWJfW2FjP4Du387w==
#password = gAAAAABo52D7sEBmtfcCv2shxybef66zojupLPMP25CTQ8Z5TzQMw8gw8CHLwJ_CN1qsg3kkIgypYqpMmsRiRuH0X5QXjhvMXQ==





#  Configuração para Oracle 
# Requer um Oracle Database rodando e o driver oracledb.
# Instale com: pip install oracledb
# 'dbname' aqui geralmente se refere ao Service Name ou SID.
#
#type = oracle
#host = localhost
#port = 1521
#dbname = NexlifyTTk
#user = gato
#password = -Vladmir!5Anos-


#  Configuração para Firebird / Interbase 
# Requer um servidor Firebird/Interbase rodando e o driver fdb.
# Instale com: pip install fdb
# 'dbname' aqui é o caminho para o arquivo .fdb ou um alias configurado no servidor.
#
#type = firebird
#host = 10.77.77.189
#port = 3050
#dbname = C:\database\NexlifyTTk.fdb
#user = gato
#password = -Vladmir!5Anos-